trains/apps/cargo/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^delete/(?P<cargo_id>\d+)', views.delete, name='delete'),
    url(r'^add', views.add, name='add'),
    url(r'^', views.index, name='index'),
]

trains/apps/login/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^enter', views.enter, name='enter'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^register', views.register, name='reg'),
]

trains/apps/main/urls.py
from django.conf.urls import include, url

import views

urlpatterns = [
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^services', views.services, name='services'),
    url(r'^tourism', views.tourism, name='tourism'),
    url(r'^corporate', views.corporate, name='corporate'),
    url(r'^$', views.index, name='index')
]

trains/apps/race/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^delete/(?P<race_id>\d+)', views.delete, name='delete'),
    url(r'^add', views.add, name='add'),
    url(r'^(?P<race_id>\d+)', views.single, name='single'),
    url(r'^$', views.index, name='index'),
]

trains/apps/station/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^delete/(?P<station_id>\d+)', views.delete, name='delete'),
    url(r'^add', views.add, name='add'),
    url(r'^', views.index, name='index'),
]

trains/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('trains.apps.login.urls', namespace='login')),
    url(r'^freight/', include('trains.apps.race.urls', namespace='race')),
    url(r'^cargos/', include('trains.apps.cargo.urls', namespace='cargo')),
    url(r'^stations/', include('trains.apps.station.urls',
                               namespace='station')),
    url(r'^', include('trains.apps.main.urls', namespace='main')),
]

trains/apps/cargo/models.py
from django.db import models


class Cargo(models.Model):
    name = models.CharField(max_length=150, null=False)

    def __unicode__(self):
        return "%s" % (self.name, )

trains/apps/login/models.py
# from django.db import models

trains/apps/main/models.py
from django.db import models

trains/apps/race/models.py
from django.db import models

from trains.apps.cargo.models import Cargo
from trains.apps.station.models import Station


class Race(models.Model):
    id_from = models.ForeignKey(Station, null=False, related_name='race_from')
    id_to = models.ForeignKey(Station, null=False, related_name='race_to')
    wagons = models.IntegerField(null=False)
    cargos = models.ManyToManyField(Cargo)

    def __unicode__(self):
        return "%s - %s" % (self.id_from.name, self.id_to.name)

    class Meta:
        ordering = ['id']

trains/apps/station/models.py
from django.db import models


class Station(models.Model):
    name = models.CharField(max_length=150, null=False)

    def __unicode__(self):
        return "%s" % (self.name, )

trains/apps/login/forms.py
from django import forms


class EnterFrom(forms.Form):
    login = forms.CharField(label='Login')
    password = forms.CharField(widget=forms.PasswordInput)

trains/apps/cargo/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required

import models


# @login_required(login_url='/auth/enter')
def index(request):
    user = auth.get_user(request).username
    cargos = models.Cargo.objects.all()
    return render(request, 'cargo/cargos.html',
                  {'cargos': cargos,
                   'username': user})


@login_required(login_url='/auth/enter')
def delete(request, cargo_id):
    models.Cargo.objects.filter(id=cargo_id).delete()
    return redirect('/cargos')


@login_required(login_url='/auth/enter')
def add(request):
    pass

trains/apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth

import forms


def enter(request):
    if request.POST:
        EnterForm = forms.EnterFrom(request.POST)
        if EnterForm.is_valid():
            login = EnterForm.cleaned_data['login']
            password = EnterForm.cleaned_data['password']
            user = auth.authenticate(username=login, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/freight')
            else:
                err_msg = 'Invalid login or password'
                return render(request, 'login/enter.html',
                              {'form': EnterForm,
                               'error': err_msg})
    else:
        EnterForm = forms.EnterFrom()
    return render(request, 'login/enter.html', {'form': EnterForm})


def logout(request):
    auth.logout(request)
    return redirect('/')


def register(request):
    pass

trains/apps/main/views.py
from django.shortcuts import render
from django.contrib import auth


def index(request):
    user = auth.get_user(request).username
    return render(request, 'main/index.html', {'username': user})


def about(request):
    user = auth.get_user(request).username
    return render(request, 'main/about.html', {'username': user})


def contact(request):
    user = auth.get_user(request).username
    return render(request, 'main/contact.html', {'username': user})


def services(request):
    user = auth.get_user(request).username
    return render(request, 'main/services.html', {'username': user})


def tourism(request):
    user = auth.get_user(request).username
    return render(request, 'main/tourism.html', {'username': user})


def corporate(request):
    user = auth.get_user(request).username
    return render(request, 'main/corporate.html', {'username': user})

trains/apps/race/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required

import models


@login_required(login_url='/auth/enter')
def index(request):
    user = auth.get_user(request).username
    races = models.Race.objects.all()
    return render(request, 'race/freight.html',
                  {'username': user,
                   'races': races})


@login_required(login_url='/auth/enter')
def delete(request, race_id):
    # user = auth.get_user(request).username
    models.Race.objects.filter(id=race_id).delete()
    return redirect('/races')


@login_required(login_url='/auth/enter')
def single(request, race_id):
    user = auth.get_user(request).username
    race = models.Race.objects.get(pk=race_id)
    return render(request, 'race/single.html',
                  {'username': user,
                   'race': race})


@login_required(login_url='/auth/enter')
def add(request):
    pass

trains/apps/station/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required

import models


# @login_required(login_url='/auth/enter')
def index(request):
    user = auth.get_user(request).username
    stations = models.Station.objects.all()
    return render(request, 'station/stations.html',
                  {'stations': stations,
                   'username': user})


@login_required(login_url='/auth/enter')
def delete(request, station_id):
    models.Station.objects.filter(id=station_id).delete()
    return redirect('/stations')


@login_required(login_url='/auth/enter')
def add(request):
    pass

trains/apps/cargo/templates/cargo/cargos.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | freight
{% endblock %}

{% block heading %}
    <h1 class="left">cargos</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li class="active"><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block aside-menu %}
    <li><a href="{% url 'race:index' %}">races</a></li>
    <li><a href="{% url 'station:index' %}">stations</a></li>
    <li><a href="{% url 'cargo:index' %}">cargos</a></li>
    {% if username %}
        <li class="in-out"><a href="{% url 'login:logout' %}">logout</a></li>
    {% else %}
        <li class="in-out"><a href="{% url 'login:enter' %}">enter</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>№</th>
                <th>Название</th>
            </tr>
        </thead>
        <tbody>
        {% for c in cargos %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ c.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p></p>
{% endblock %}

trains/apps/login/templates/login/enter.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'login/css/enter.css' %}" type="text/css" />
{% endblock %}


{% block title %}
    Railways | enter
{% endblock %}

{% block heading %}
    <h1 class="left">enter</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content-wrapper %}
    <section>
    <form id="loginForm" action="{% url 'login:enter' %}" method="post" >
        {% csrf_token %}
        {% if error %}
            <p id="error_message">{{ error }}</p>
        {% endif %}
        {{ form }}
        <input type="submit" value="login" />
    </form>
    </section>
{% endblock %}

trains/apps/main/templates/main/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | about us
{% endblock %}

{% block heading %}
    <h1 class="left">about us</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li  class="active"><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content %}
    <p></p>
{% endblock %}

trains/apps/main/templates/main/contact.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | contacts
{% endblock %}

{% block heading %}
    <h1 class="left">contacts</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li class="active"><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block aside-menu %}
    <li><a href="#">appeals</a></li>
    <li><a href="#">advertising</a></li>
    <li><a href="#">administrative procedures</a></li>
    {% if username %}
        <li class="in-out"><a href="{% url 'login:logout' %}">logout</a></li>
    {% else %}
        <li class="in-out"><a href="{% url 'login:enter' %}">enter</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <p>
        <span class="content-p-header">
            Вы можете направить в адрес руководства Белорусской железной дороги
        </span>
        <ul>
            <li>письмо: ул. Ленина,17, г. Минск, 220030, Республика Беларусь </li>
            <li>факс: (+375 17) 327 56 48;</li>
            <li>электронное сообщение: ns@rw.by.</li>
        </ul>
    </p>

    <p>
        <span class="content-p-header">
            Администратор корпоративного Интернет-сайта
        </span>
        <p>
        Свои пожелания и замечания по вопросам работы корпоративного Интернет-сайта Белорусской железной дороги
        Вы можете направить по адресу <a href="ktc@upr.mnsk.rw.by">ktc@upr.mnsk.rw.by</a>
        </p>
    </p>
{% endblock %}

trains/apps/main/templates/main/corporate.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | corporate
{% endblock %}

{% block heading %}
    <h1 class="left">corporate</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li class="active"><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content %}
{% endblock %}

trains/apps/main/templates/main/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | home
{% endblock %}

{% block heading %}
    <h1 class="left">home</h1>
{% endblock %}

{% block  top-menu %}
    <li class="active"><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li ><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content %}
<blockquote>
    <p> “You know you're in love when you can't fall asleep because reality is finally better than your dreams.”
    </p>
    <cite>Dr. Seuss</cite>
    </blockquote>
    <p>
        <span class="content-p-header"></span>
        About this author edit data
        Theodor Seuss Geisel was born 2 March 1904 in Springfield, MA. He graduated Dartmouth College in 1925, and proceeded on to Oxford University with the intent of acquiring a doctorate in literature. At Oxford he met Helen Palmer, who he wed in 1927. He returned from Europe in 1927, and began working for a magazine called Judge, the leading humor magazine in America at the time, submitting both cartoons and humorous articles for them. Additionally, he was submitting cartoons to Life, Vanity Fair and Liberty. In some of his works, he'd made reference to an insecticide called Flit. These references gained notice, and led to a contract to draw comic ads for Flit. This association lasted 17 years, gained him national exposure, and coined the catch
    </p>
    <p>
        About this author edit data
        Theodor Seuss Geisel was born 2 March 1904 in Springfield, MA. He graduated Dartmouth College in 1925, and proceeded on to Oxford University with the intent of acquiring a doctorate in literature. At Oxford he met Helen Palmer, who he wed in 1927. He returned from Europe in 1927, and began working for a magazine called Judge, the leading humor magazine in America at the time, submitting both cartoons and humorous articles for them. Additionally, he was submitting cartoons to Life, Vanity Fair and Liberty. In some of his works, he'd made reference to an insecticide called Flit. These references gained notice, and led to a contract to draw comic ads for Flit. This association lasted 17 years, gained him national exposure, and coined the catch
    </p>
    <p>
        About this author edit data
        Theodor Seuss Geisel was born 2 March 1904 in Springfield, MA. He graduated Dartmouth College in 1925, and proceeded on to Oxford University with the intent of acquiring a doctorate in literature. At Oxford he met Helen Palmer, who he wed in 1927. He returned from Europe in 1927, and began working for a magazine called Judge, the leading humor magazine in America at the time, submitting both cartoons and humorous articles for them. Additionally, he was submitting cartoons to Life, Vanity Fair and Liberty. In some of his works, he'd made reference to an insecticide called Flit. These references gained notice, and led to a contract to draw comic ads for Flit. This association lasted 17 years, gained him national exposure, and coined the catch
    </p>
{#			<figure>#}
{#				<img src="{% static 'images/sample.png' %}" width="320" height="175"/>#}
{#			</figure>#}
{#			<figure>#}
{#				<img src="{% static 'images/sample.png' %}" width="320" height="175"/>#}
{#			</figure>#}
    <h2>OUR TEAM</h2>
    <div class="team-row">
        <figure>
            <img src="{% static 'images/sample.png' %}" width="96" height="96" alt=""/>
            <figcaption>Budko Sergey Vladimirovich<span>chief</span></figcaption>
        </figure>
        <figure>
            <img src="{% static 'images/sample.png' %}" width="96" height="96" alt=""/>
            <figcaption>Velichko Mihail Valer'evich<span>deputy chief</span></figcaption>
        </figure>
        <figure>
            <img src="{% static 'images/sample.png' %}" width="96" height="96" alt=""/>
            <figcaption>Arnaut Sergei Yakovlevich<span>financial calc.</span></figcaption>
        </figure>
        <figure>
            <img src="{% static 'images/sample.png' %}" width="96" height="96" alt=""/>
            <figcaption>Krovsh Nikolay Mihailovich<span>dev ASU & ERP</span></figcaption>
        </figure>
        <figure>
            <img src="{% static 'images/sample.png' %}" width="96" height="96" alt=""/>
            <figcaption>Semuha Pavel Pavlovich<span>social</span></figcaption>
        </figure>
    </div>
{% endblock %}

trains/apps/main/templates/main/services.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | services
{% endblock %}

{% block heading %}
    <h1 class="left">services</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li class="active"><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content %}
{% endblock %}

trains/apps/main/templates/main/tourism.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | tourism
{% endblock %}

{% block heading %}
    <h1 class="left">tourism</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li class="active"><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block content %}
{% endblock %}

trains/apps/race/templates/race/freight.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | freight
{% endblock %}

{% block heading %}
    <h1 class="left">races</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li class="active"><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block aside-menu %}
    <li><a href="{% url 'race:index' %}">races</a></li>
    <li><a href="{% url 'station:index' %}">stations</a></li>
    <li><a href="{% url 'cargo:index' %}">cargos</a></li>
    {% if username %}
        <li class="in-out"><a href="{% url 'login:logout' %}">logout</a></li>
    {% else %}
        <li class="in-out"><a href="{% url 'login:enter' %}">enter</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>№</th>
                <th>Откуда</th>
                <th>Куда</th>
                <th>Вагоны</th>
            </tr>
        </thead>
        <tbody>
        {% for race in races %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ race.id_from.name }}</td>
                <td>{{ race.id_to.name }}</td>
                <td>{{ race.wagons }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p></p>
{% endblock %}

trains/apps/race/templates/race/single.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'main/css/table.css' %}" type="text/css" />
    <script src="{% static 'race/js/table_href.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <p>{{ race.id_from.name }} - {{ race.id_to.name }}</p>
    <ul>
    {% for cargo in race.cargos.all %}
        <li>{{ cargo.name }}</li>
    {% endfor %}
    </ul>
{% endblock %}

trains/apps/station/templates/station/stations.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Railways | freight
{% endblock %}

{% block heading %}
    <h1 class="left">stations</h1>
{% endblock %}

{% block  top-menu %}
    <li><a href="{% url 'main:index' %}">home</a></li>
    <li><a href="{% url 'main:about' %}">about us</a></li>
    <li><a href="{% url 'main:services' %}">services</a></li>
    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
    <li class="active"><a href="{% url 'race:index' %}">freight</a></li>
    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
{#				<li><a href="">careers</a></li>#}
    <li><a href="{% url 'main:contact' %}">contacts</a></li>
{% endblock %}

{% block aside-menu %}
    <li><a href="{% url 'race:index' %}">races</a></li>
    <li><a href="{% url 'station:index' %}">stations</a></li>
    <li><a href="{% url 'cargo:index' %}">cargos</a></li>
    {% if username %}
        <li class="in-out"><a href="{% url 'login:logout' %}">logout</a></li>
    {% else %}
        <li class="in-out"><a href="{% url 'login:enter' %}">enter</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>№</th>
                <th>Название</th>
            </tr>
        </thead>
        <tbody>
        {% for st in stations %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ st.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p></p>
{% endblock %}

trains/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    {% block head %}
	<meta http-equiv="Content-type" content="text/html" charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">

	<title>{% block title %}Railways{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">

	<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% endblock %}
</head>
<body>
	<div id="wrapper">
		<header>
            {% block header %}
			<a href="{% url 'main:index' %}"><img src="{% static 'images/logo.png' %}" alt="railways logo" /></a>
			<form name="search" action="#" method="get">
				<input class="search-input" type="text" name="q" placeholder="search"/><button type="submit">GO</button>
			</form>
            {% endblock %}
		</header>
		<nav>
			<ul class="top-menu">
                {% block  top-menu %}
				    <li><a href="{% url 'main:index' %}">home</a></li>
                    <li><a href="{% url 'main:about' %}">about us</a></li>
                    <li><a href="{% url 'main:services' %}">services</a></li>
                    <li><a href="{% url 'main:tourism' %}">tourism</a></li>
                    <li><a href="{% url 'main:freight' %}">freight</a></li>
                    <li><a href="{% url 'main:corporate' %}">corporate</a></li>
                {#				<li><a href="">careers</a></li>#}
                    <li><a href="{% url 'main:contact' %}">contacts</a></li>
			    {% endblock %}
            </ul>
		</nav>
		<div id="heading">
            {% block heading %}
			<h1 class="left">railways</h1>
            {% endblock %}
		</div>
		<div class="content-wrapper">
        {% block content-wrapper %}
        <aside>
			<nav>
				<ul class="aside-menu">
                    {% block aside-menu %}
					<li><a href="">ticket sales</a></li>
					<li><a href="">buy online</a></li>
					<li><a href="">discounts</a></li>
                    {% if username %}
                        <li class="in-out"><a href="{% url 'login:logout' %}">logout</a></li>
                    {% else %}
                        <li class="in-out"><a href="{% url 'login:enter' %}">enter</a></li>
                    {% endif %}
{#					<li><a href="">LOREM IPUSUM</a></li>#}
{#					<li><a href="">LOREM IPUSUM</a></li>#}
{#					<li><a href="">LOREM IPUSUM</a></li>#}
				    {% endblock %}
                </ul>
			</nav>
			<h2>our offices</h2>
			<p><img src="{% static 'images/sample.png' %}" width="230" height="180" alt="our offices"/></p>
		</aside>
		<section>
            {% block content %}

            {% endblock %}
		</section>
        {% endblock %}
        </div>
	</div>
	<footer>
		<div id="footer">
            {% block footer %}
			<div id="twitter">
				<h3>twitter feed</h3>
				<time datetime="2015-07-01"><a href="">23 oct</a></time>
				<p>#asdfa sadfp asof pa pasdf #asda #fkf</p>
			</div>
			<div id="sitemap">
				<h3>sitemap</h3>
				<div>
					<a href="#">Home</a>
					<a href="#">About</a>
					<a href="#">Services</a>
				</div>
				<div>
					<a href="#">Partners</a>
					<a href="#">Support</a>
					<a href="#">Contact</a>
				</div>
			</div>
			<div id="social">
			    <h3>SOCIAL NETWORKS</h3>
			    <a href="http://twitter.com/" class="social-icon twitter"></a>
			    <a href="http://facebook.com/" class="social-icon facebook"></a>
			    <a href="http://plus.google.com/" class="social-icon google-plus"></a>
			    <a href="http://vimeo.com/" class="social-icon-small vimeo"></a>
			    <a href="http://youtube.com/" class="social-icon-small youtube"></a>
			    <a href="http://flickr.com/" class="social-icon-small flickr"></a>
			    <a href="http://instagram.com/" class="social-icon-small instagram"></a>
			    <a href="/rss/" class="social-icon-small rss"></a>
			</div>
			<div id="copyright">
				<a href="{% url 'main:index' %}"><img src="{% static 'images/footer-logo.png' %}" /></a>
				<p>Copyright &copy 2015 devforyou</p>
			</div>
            {% endblock %}
		</div>
	</footer>
</body>
</html>